### PR TITLE
Added google calendar link to sync up with Pydelhi Calender on google calendar

### PR DESCRIPTION
**Pull request by vinaykrdahiya**
Maybe a overkill but helps in having a central place following can be done:
- Creating and syncing up community activities with google calendar seamlessly just takes one click to import it to your calendar.
- Create repeating events like hangout session from central location then adding through personal google calendar.

### CODE REVIEW

**Comment by saurabh-fueled** [comment]
> just takes one click to import it to your calendar.

Sorry for sounding foolish, but how can I do this?

**Comment by theskumar** [comment]
>  just takes one click to import it to your calendar.

Sorry for sounding foolish, but how can I do it?

**Comment by theskumar** [comment]
I think i got how to do: 

as

Is it possible not to expose the gmail id? possible to use a proper name for the calendar? like I've a calender added and it's called `Holidays in India`

**Comment by theskumar** [comment]
Another thing that is coming to my mind is that, even if I know there is a hangout session at that time, how can we make it easier for people to get notified before event and provide a proper way to join the hangout as well.

**Comment by vinaykrdahiya** [comment]
I am not sure how to do that. but currently google calendar gave the calendar id as the email itself.

    Another thing that is coming to my mind is that, even if I know there is a hangout session at that time, how can we make it easier for people to get notified before event and provide a proper way to join the hangout as well.

That's why i thought generally people keep calendar or gmail synced up. So this can give them a notification before 30 minutes prior to the hangout once you import it to your calendar.

**Comment by theskumar** [comment]
ok. and sounds good to start with. let's see how it goes.

**Comment by theskumar** [comment]
Added your code to master https://github.com/pydelhi/pydelhi.github.io/commit/5a7fb2450d2a65a597fd554025596b2c86ea77ef :)

**Pull request closed without merging**
