### PR TITLE
add support for latest blog posts to be displayed on home page

### PR DESCRIPTION
**Pull request by kartikanand**

### CODE REVIEW

**Comment by theskumar** [comment]
I've add my side of changes, possible you can test it out and see if things are working properly.

**Comment by kartikanand** [comment]
Thanks Saurabh! (especially for cleaning up the code). I'll test it out and revert.

Though, I can see you've removed the description as well, we don't need it?

**Comment by theskumar** [comment]
nah. description was taking a lot of real-state area without adding much value. I might add date and a subscribe link, but will have to work out the design and placement for that, these two features can go as in next iteration.

**Comment by kartikanand** [comment]
Looks fine now (phew...)

http://www.kartikanand.com/pydelhi.github.io/

**Comment by theskumar** [comment]
Amazing thanks! 🎉

**Pull request merged**
