### PR TITLE
show sponsors on home page

### PR DESCRIPTION
**Pull request by kartikanand**
Hi Saurabh,

Using the same techniques as blog posts commit, I've added some code to display sponsors as mentioned in issue #29 

You can view the changes here:
http://www.kartikanand.com/pydelhi.github.io/

I'm not proficient in CSS, so there may be subtle things that I may have missed :)
Let me know about your suggestions and feedback. 

Thanks,
Kartik

### CODE REVIEW

**Comment by kartikanand** [comment]
Another thought came to my mind, do our sponsors change so rapidly that we need to dynamically pull in the list from meetup API ?

Wouldn't a static list already present in HTML be better in this case ?

**Comment by theskumar** [comment]
This looks amazing! I'll take a stab at the making the list little more usable. 

The list update frequency is max once or twice a month. The issue is duplication of data and volunteer's effort to add it at multiple places. 

We also have a https://pydelhi.org/sponsorship/ page where this snippet can be used or at other places. 

Sponsors are a major component in making this community self-sustaining. So better visibility for them is a win for us.

**Comment by theskumar** [comment]
The issue with https://pydelhi.org/sponsorship/ is that even though they are hard-coded and without any third-party api, they are upto date. Reason? I've already mentioned above.

**Comment by kartikanand** [comment]
Yes this sounds reasonable. If we want to include detailed info about sponsors then I guess https://pydelhi.org/sponsorship/ is better since we wouldn't want to clutter the home page much.

**Comment by satyaakam** [comment]
@kartikanand make the page name as sponsors instead of sponsorship , if we are calling it sponsorship then we should write something about it like what it means etc , apart from that i want to see some form of menu in this page as well or how can i navigate back to the home page

**Pull request closed without merging**
